[DEVICE]
LastDateTime=14.09.2018 10:18:06
Location=ООО "ХАЛИБАС"
Description=Насос
ID=00000500 DExS.SMFCB v1.10 30.08.2018 www.intmash.ru
MCU=1

[RAM]
p00020=DExS_PWR_OK/Качество сети выпрямителя и исправность DExS.PWR/TBit/x0000/1/r0000.0/0/1/0/
p00021=DExS_PWR_LNK/Наличие связи с платой DExS.PWR/TBit/x0000/2/r0000.1/0/1/0/
p00022=SyncRect/Наличие синхроимпульсов выпрямителя/TBit/x0000/4/r0000.2/0/1/0/
p00023=PWR/Выпрямитель включен/TBit/x0000/8/r0000.3/0/1/0/
p00024=Chop/Инвертирование/TBit/x0000/16/r0000.4/0/1/0/
p00025=ExtRegTimeOut/Приостановка автоматического регулятор/TBit/x0000/32/r0000.5/0/1/0/
p00026=R_INSL_LOW/Предупредительный порог изоляции/TBit/x0000/64/r0000.6/0/1/0/
p00027=T1000//TBit/x0000/128/r0000.7/0/1/0/

;///////////////////////////////////////////////////////////////////
p00600=Ustat/Напряжение статора/TWORD/x000C/r0006/B/1/2/0/
p00700=Istat/Ток статора/TWORD/x000E/r0007/A/1/2/0/
p00800=Istat_max/Ток статора "грубо"/TWORD/x0010/r0008/A/1/2/0/
p00900=Ur/Напряжение ротора/TInteger/x0012/r0009/B/1/2/0/
p01000=Ir/Ток ротора/TInteger/x0014/r000A/A/1/2/0/
p01100=IttA/Ток выпрямителя ТТА/TWORD/x0016/r000B/A/1/2/0/
p01200=IttB/Ток выпрямителя ТТВ/TWORD/x0018/r000C/A/1/2/0/
p01300=IttC/Ток выпрямителя ТТС/TWORD/x001A/r000D/A/1/2/0/


[CD]


;Наклон калибровка аналоговых параметров платы DExS.CPU
p61800=Kadc_Ustat//TFloat/xE024/rC012/*/1/4/0/x40E9999A/
p62000=Kadc_Istat//TFloat/xE028/rC014/*/1/4/0/x3DB645A2/
p62200=Kadc_Istat_max//TFloat/xE02C/rC016/*/1/4/0/x3E947AE1/
p62400=Kadc_Uload//TFloat/xE030/rC018/*/1/4/0/x3DF5C28F/
p62600=Kadc_Iload//TFloat/xE034/rC01A/*/1/4/0/x3E189D8A/
p62800=Kadc_In1//TFloat/xE038/rC01C/*/1/4/0/x3ED30684/
p63000=Kadc_In2//TFloat/xE03C/rC01E/*/1/4/0/x3EDAC7A3/
p63200=Kadc_In3//TFloat/xE040/rC020/*/1/4/0/x3ED7629A/


;Уставки связи
p65301=Modbus_option_DVA/адрес/TByte/xE06A/rC035.L/*/1/1//0/x01/
p65302=Modbus_option_BPS/скорость/TPrmList/xE06B/rC035.H/BPS//x04#115200/x03#57600/x02#19200/x01#9600/x04/
p65401=Modbus_USB_DVA/адрес/TByte/xE06C/rC036.L/*/1/1//0/x01/
p65402=Modbus_USB_BPS/скорость/TPrmList/xE06D/rC036.H/BPS//x07#921600/x06#460800/x05#230400/x04#115200/x03#57600/x02#19200/x01#9600/x04/
p65501=Modbus_RS485_DVA/адрес/TByte/xE06E/rC037.L/*/1/1//0/x01/
p65502=Modbus_RS485_BPS/скорость/TPrmList/xE06F/rC037.H/BPS//x04#115200/x03#57600/x02#19200/x01#9600/x04/   

[FLASH]
p10000=IstStart/Пуск по току статора/TWORD/xF000/r2000/A/1/2//1/x0014/
p10100=IstStop/Стоп по току статора/TWORD/xF002/r2001/A/1/2//1/x000A/
p10200=IstExcEnable/Допустимый ток статора перед подачей возбуждения/TWORD/xF004/r2002/A/1/2//1/x0190/
p10300=ExcEnableFreq/Минимальная частота скольжения перед подачей возбуждения/TWORD/xF006/r2003/Hz/0.1/2//1/x0019/
p10400=HsFreq/(Тяжёлый пуск)Максимальная частота скольжения перед подачей возбуждения/TWORD/xF008/r2004/Hz/0.1/2//1/x0032/
p10500=HsTime/Время тяжёлого пуска/TWORD/xF00A/r2005/sec/1/2//1/x0014/
p10600=IExcRef/Ток возбуждения в ручном режиме/TWORD/xF00C/r2006/А/1/2//1/x00C8/
p10700=IExcTst/Ток проверки цепи скольжения/TWORD/xF00E/r2007/А/1/2//1/x0064/

;iCM.HCK
p21000=IP ADDR/IP адрес сетевой карты/TIPAddr/xF0CC/r2066/-/1/4/xC0A80064/

[EVENTS]
;авариии
0=FAULT/a/0/Аварий//
;информация
1=PWR/i/0/Выпрямитель включен/На тиристоры выпрямителя поданы импульсы управления/
2=Test/i/0/Режим опробования/Возбудитель включен в режим опробования (проверка цепи скольжения и уставки рабочего тока в ручном режиме)/
3=iMMSState/i/0/Выключатель включен/БК выключателя в состоянии "Включен"/
4=StartProcEnable/i/0/Двигатель включен//
5=oREADY_K2/i/0/Готовность к работе/Готовность к работе 1-разрешена, 0-запрещена/


[STAT]
CNT0=0:0,0:1/2/0/Время работы контроллера (в секундах)/
CNT1=4:1/2/0/Время работы двигателя(в секундах)/

[vars]
AINK=0,00388
CINScale=0,0226
