name: Deploy to GitHub Pages

# Триггер: запускать workflow при каждом пуше в ветки main или Type_Script
on:
  push:
    branches:
      - main
      - Type_Script
  workflow_dispatch:

# Устанавливаем права для работы с GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Управляем очередью развертывания
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Указываем папку для загрузки
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4