name: Deploy to GitHub Pages

# Триггер: запускать workflow при каждом пуше в ветку main
on:
  push:
    branches:
      - main
      - Type_Script

  # Позволяет запускать этот workflow вручную из вкладки Actions на GitHub
  workflow_dispatch:

# Устанавливаем права для работы с GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Управляем очередью развертывания (чтобы новые пуши корректно сменяли старые)
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest  # Удалите все строки environment и url
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Указываем, какую папку загружать. 
          # Так как index.html лежит в корне, ставим точку "."
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4